#include "images.h"

const ext_img_desc_t images[30] = {
    { "Rocket_Launch", &img_rocket_launch },
    { "Very_Smiley", &img_very_smiley },
    { "Excited_Smiley", &img_excited_smiley },
    { "Steps", &img_steps },
    { "Heart_Rate", &img_heart_rate },
    { "Altitude", &img_altitude },
    { "Bolt", &img_bolt },
    { "Earth", &img_earth },
    { "Back Arrow", &img_back_arrow },
    { "Back Arrow 44p", &img_back_arrow_44p },
    { "Running", &img_running },
    { "Workout", &img_workout },
    { "Weather Cloudy", &img_weather_cloudy },
    { "Notifications", &img_notifications },
    { "Clock", &img_clock },
    { "Stopwatch", &img_stopwatch },
    { "Settings", &img_settings },
    { "Plus", &img_plus },
    { "Stats_24p", &img_stats_24p },
    { "Minus", &img_minus },
    { "Pause", &img_pause },
    { "Play", &img_play },
    { "Flame_50p", &img_flame_50p },
    { "Bin", &img_bin },
    { "Speed", &img_speed },
    { "Flame_32p", &img_flame_32p },
    { "Compress", &img_compress },
    { "Weather Sunny", &img_weather_sunny },
    { "road", &img_road },
    { "Blood_oxygen", &img_blood_oxygen },
};
